/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    // "test",
    // "intro",
    {
      type: "category",
      label: "介绍",
      items: [
        "intro/01xiaobaimanpaying",
        "intro/02duidugongxuehuodong",
        "intro/03kaifangke",
        "intro/04zuishaobiyaobianchengke",
        "intro/05xiangmuqun",
      ],
    },
    {
      type: "category",
      label: "开放课",
      items: ["open-course/01list", "open-course/02markdown", "open-course/03github"],
    },
    "about",
  ],
};

module.exports = sidebars;
